[main]
title = "radhitya.org"
subtitle = "personal site"
url = "https://radhitya.org"
output = "public"
amount = 5

[[submenu]]
name = "home"
url = "/"

[[submenu]]
name = "blog"
url = "/blog"

[[submenu.children]]
name = "baboutx"
url = "/babout"

[[submenu]]
name = "about"
url = "/about"

[[submenu.children]]
name = "aboutx"
url = "/about"
